### ISSUE TITLE
"zone.js" version restriction

### ISSUE THREAD

**Issue by hakimio** [Seemspyo/ngx-smooth-scroll#13]
After updating Angular to v11.2 and zone.js to v0.11.4, yarn started complaining that `@eunsatio/ngx-smooth-scroll@1.0.5" has incorrect peer dependency "zone.js@^0.10.0"`.
Everything seems to be working fine after the upgrade, but would be nice to get rid of the warning. Can you either remove "zone.js" from peer dependencies or use some broader match (`"zone.js": ">=0.10.0"` or `"zone.js": "*"`)?

**Comment by Seemspyo** [comment]
I have met a lot of warnings about dependencies in node projects, I usually ignore them since author update peer dependencies without cares, that might be a project breaker.

But I think `zone.js` and `tslib` are not necessary. I remove does in fd5fa74.

**Comment by hakimio** [comment]
Thanks for fixing this and sorry for late response.

- I agree that `zone.js` is not used directly by this library (some references only in tests) and it shouldn't depend on it.
- `tslib` is required by all TypeScript applications but it's added to "hard" dependencies automatically by Angular. You don't have to manually add it yourself. You can check the `package.json` in the attached npm package to see that `tslib` dependency is in the generated `package.json`.
```json
"dependencies": {
    "tslib": "^1.10.0"
  }
```

[eunsatio-ngx-smooth-scroll-1.0.6.zip](https://github.com/Seemspyo/ngx-smooth-scroll/files/6458085/eunsatio-ngx-smooth-scroll-1.0.6.zip)
